### ISSUE TITLE
Bug: Missing Mime Type Handling for get_file_info()

### ISSUE THREAD

**Issue by Gi7w0rm** [tsale/TeleTracker#15]
The get_file_info() function in TeleViewer.py is missing handling for Telegram Stickers.
This is not necessarily a problem as stickers have little informational value. 
However, both the return function and the Exception do not return 2 but only one None Type object.
This leads to a missing file_id.

To fix: 
add a `, None` in lines
https://github.com/tsale/TeleTracker/blob/0515b67fdba3e62e8f7d3acf2966607df90aaa42/helpers/TeleViewer.py#L35
https://github.com/tsale/TeleTracker/blob/0515b67fdba3e62e8f7d3acf2966607df90aaa42/helpers/TeleViewer.py#L38

**Comment by Gi7w0rm** [comment]
Additionally, you can pack the code block from here: 
https://github.com/tsale/TeleTracker/blob/0515b67fdba3e62e8f7d3acf2966607df90aaa42/helpers/TeleViewer.py#L71
to 
https://github.com/tsale/TeleTracker/blob/0515b67fdba3e62e8f7d3acf2966607df90aaa42/helpers/TeleViewer.py#L90
into an if statement:

`if file_id is not None:`

**Comment by AnaxyJod** [comment]
But still I'm getting this error 
Error: 'NoneType' object has no attribute 'file_id'           Error: 'NoneType' object has no attribute 'file_id'
