### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by schizophrenic144** [tsale/TeleTracker#21]
So many bugs that its just insane. I do NOT recommend

**Comment by tsale** [comment]
You found bugs? What a genius! If only fixing bugs was as easy as spotting your lack of coding skills. 

I'll make sure to create a version that even rocks could use, just for you.

**Comment by schizophrenic144** [comment]
Why the FUCK would i have to fix bugs you cant even fix 🤣. You were so butthurt over this issue that you had to change the title too. Incompetent dick

**Comment by schizophrenic144** [comment]
Forgot to mention the speed that it gets the messages, 10 messages every 27 seconds

**Comment by tsale** [comment]
lol 😂😂 Sure. Trying to use my code without even knowing what an API is can be quite the leap. Imma block you soon, but I'd be interested to know who's behind that account of yours 🙂 Big fun of your repositories. I also love your GitHub follows (🇷🇺). I am sorry if I am ruining your business (not sorry). I hope all of your bots will be deleted eventually by telegram and your chats will be deleted by the community. You must be really hurting from a tool like mine 🙂

*PS - The title change is called trolling 😂
