### ISSUE TITLE
[TIP] Temporary files and Saved in a dedicated directory

### ISSUE THREAD

**Issue by drego85** [tsale/TeleTracker#5]
Hello,
after one day of use I found the main directory of TeleTracker full of temporary files (sqlite, txt and json of saved messages).

To keep it more tidy and clean why don't we store these files in a subdirectory? We could always use the "download" directory.

I didn't create a PR directly because I wanted to compare with you first. 

Thanks

**Comment by tsale** [comment]
Thank you for the suggestion @drego85! I added this in dev-1 and will merge to main shortly 🙂

![CleanShot 2024-04-28 at 16 42 06@2x](https://github.com/tsale/TeleTracker/assets/25332397/48024d72-1770-4750-b7cb-8267e39f7a58)

I also added sessions under their own directory to keep it clean.
