### ISSUE TITLE
Unicode error on retriving message

### ISSUE THREAD

**Issue by Fahmi-S** [tsale/TeleTracker#8]

**Comment by tsale** [comment]
@Fahmi-S Can you provide more details? Steps to reproduce? Any details of the error?

**Comment by Fahmi-S** [comment]
> @Fahmi-S Can you provide more details? Steps to reproduce? Any details of the error?

So its been a while Yeah, what I remember is when I tried to retrieve a message from Telegram. I got an error because of the unicode or emoji. I fixed it by adding utf-8 to the televiewer.py.
